version: '3'
services:
  litecart:
    container_name: litecart
    restart: unless-stopped
    expose:
      - 8080:8080
    volumes:
      - ./lc_base:/lc_base
      - ./lc_digitals:/lc_digitals
      - ./lc_uploads:/lc_uploads
      - ./site:/site
    image: shurco/litecart:latest
